name: Linting

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
      - name: Install dependencies
        run: npm ci
      - name: Run ESLint
        run: ./node_modules/.bin/eslint .
